//! MagiaMagica CLI — Rust 関数を魔法陣として描画する (Phase 1.7, M7)。
//!
//! サブコマンド:
//! - `magia render <FILE> --fn <NAME>` — SVG を出力
//! - `magia list <FILE>` — 関数一覧
//! - `magia emit-ir <FILE> --fn <NAME>` — MagiaIR を JSON で出力 (デバッグ用)

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};

use magia_core::layout::layout;
use magia_core::render::{RenderStyle, render};
use magia_rust::{list_functions, parse_function};

#[derive(Parser)]
#[command(name = "magia", version, about = "コードを魔法陣として描画する装置")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Rust 関数をミッドチルダ式の魔法陣 SVG として描画する
    Render {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 描画する関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// 描画するレイヤー (カンマ区切り)。省略時は全レイヤー
        #[arg(long, value_delimiter = ',', value_name = "LAYERS")]
        layers: Option<Vec<String>>,
        /// 出力先 SVG パス。省略時は標準出力
        #[arg(short, long, value_name = "OUT.svg")]
        output: Option<PathBuf>,
    },
    /// ファイル内の関数一覧を表示する
    List {
        /// 入力 Rust ソースファイル
        file: PathBuf,
    },
    /// MagiaIR を JSON で標準出力する (デバッグ用)
    #[command(name = "emit-ir")]
    EmitIr {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 対象の関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
    },
}

/// 描画レイヤー名 (spec §6.1.5)。CLI ではこの snake_case 名で受け、
/// SVG class の `layer-<kebab-case>` に対応づける。
const KNOWN_LAYERS: &[(&str, &str)] = &[
    ("control_flow", "layer-control-flow"),
    ("effects", "layer-effects"),
    ("type_info", "layer-type-info"),
];

fn main() {
    if let Err(error) = run(Cli::parse()) {
        eprintln!("エラー: {error:#}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<()> {
    match cli.command {
        Command::Render {
            file,
            fn_name,
            layers,
            output,
        } => {
            let selected = validate_layers(layers.as_deref())?;
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let placed = layout(&graph);
            let mut svg = render(&graph, &placed, RenderStyle::MidchildaConcentric);
            if let Some(selected) = selected {
                svg = filter_layers(&svg, &selected);
            }
            let svg = format!(
                "<!-- generated by magia-cli v{} -->\n{svg}",
                env!("CARGO_PKG_VERSION")
            );
            match output {
                Some(path) => fs::write(&path, svg)
                    .with_context(|| format!("SVG を書き出せません: {}", path.display()))?,
                None => print!("{svg}"),
            }
            Ok(())
        }
        Command::List { file } => {
            let source = read_source(&file)?;
            let names = list_functions(&source).map_err(|e| prettify_parse_error(&e))?;
            if names.is_empty() {
                eprintln!("関数が見つかりませんでした");
            }
            for name in names {
                println!("{name}");
            }
            Ok(())
        }
        Command::EmitIr { file, fn_name } => {
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let json =
                serde_json::to_string_pretty(&graph).context("IR の JSON 変換に失敗しました")?;
            println!("{json}");
            Ok(())
        }
    }
}

fn read_source(path: &Path) -> Result<String> {
    if path.extension().and_then(|e| e.to_str()) != Some("rs") {
        // Phase 1 の解析対象は Rust のみ。間違いの早期発見のため警告する (続行はする)。
        eprintln!(
            "警告: `{}` は .rs ファイルではありません (Phase 1 の解析対象は Rust のみ)",
            path.display()
        );
    }
    fs::read_to_string(path)
        .with_context(|| format!("ファイルを読み込めません: {}", path.display()))
}

fn parse_source(source: &str, fn_name: &str) -> Result<magia_core::ir::MagiaGraph> {
    parse_function(source, fn_name).map_err(|e| prettify_parse_error(&e))
}

/// `magia-rust` のエラーをユーザー向けの日本語メッセージに整える。
/// 構文エラーは syn の span から行・列を取り出して付加する
/// (`Display` 単体ではメッセージしか出ない)。
fn prettify_parse_error(error: &magia_rust::Error) -> anyhow::Error {
    match error {
        magia_rust::Error::Syntax(syntax) => {
            let start = syntax.span().start();
            anyhow::anyhow!(
                "{error} ({}行目 {}文字目付近)",
                start.line,
                start.column + 1
            )
        }
        magia_rust::Error::FunctionNotFound { .. } => anyhow::anyhow!("{error}"),
    }
}

/// `--layers` の検証。未知のレイヤー名はタイポ防止のためエラーにする。
/// 戻り値は残すべき SVG class 名の集合。`None` は「全レイヤー」。
fn validate_layers(layers: Option<&[String]>) -> Result<Option<Vec<&'static str>>> {
    let Some(layers) = layers else {
        return Ok(None);
    };
    let mut classes = Vec::new();
    for name in layers {
        match KNOWN_LAYERS.iter().find(|(known, _)| known == name) {
            Some((_, class)) => classes.push(*class),
            None => bail!(
                "未知のレイヤー名 `{name}` (使用可能: {})",
                KNOWN_LAYERS
                    .iter()
                    .map(|(known, _)| *known)
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        }
    }
    Ok(Some(classes))
}

/// 選択されなかったレイヤーの `<g class="layer-*">...</g>` ブロックを取り除く。
///
/// レンダラの出力規約 (1行1要素、レイヤー `<g>` は入れ子なし) に依存した
/// 行単位フィルタ。規約は magia-core の `midchilda.rs` 冒頭に明記されている。
fn filter_layers(svg: &str, keep_classes: &[&str]) -> String {
    // 比較パターンはループ外で1回だけ構築する。
    let keep_patterns: Vec<String> = keep_classes
        .iter()
        .map(|class| format!("\"{class}\""))
        .collect();
    let mut out = String::with_capacity(svg.len());
    let mut skipping = false;
    for line in svg.lines() {
        if !skipping && line.starts_with("<g class=\"layer-") {
            let keep = keep_patterns.iter().any(|pat| line.contains(pat.as_str()));
            if !keep {
                skipping = true;
                continue;
            }
        } else if skipping {
            if line == "</g>" {
                skipping = false;
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    // skipping のまま終わる = 閉じタグ規約が破られた (出力を黙って捨てる前に検出する)。
    debug_assert!(
        !skipping,
        "filter_layers: </g> が閉じられなかった。midchilda.rs の出力規約を確認せよ"
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_layers_accepts_known_names() {
        let layers = vec!["control_flow".to_string(), "effects".to_string()];
        let classes = validate_layers(Some(&layers)).unwrap().unwrap();
        assert_eq!(classes, vec!["layer-control-flow", "layer-effects"]);
    }

    #[test]
    fn validate_layers_rejects_unknown_name() {
        let layers = vec!["controlflow".to_string()];
        let error = validate_layers(Some(&layers)).unwrap_err();
        assert!(error.to_string().contains("未知のレイヤー名"));
        assert!(error.to_string().contains("control_flow"));
    }

    #[test]
    fn filter_layers_drops_unselected_block() {
        let svg = "<svg>\n<g class=\"layer-control-flow\">\n<circle/>\n</g>\n<g class=\"layer-effects\">\n<rect/>\n</g>\n</svg>\n";
        let filtered = filter_layers(svg, &["layer-effects"]);
        assert!(!filtered.contains("circle"));
        assert!(filtered.contains("rect"));
        assert!(filtered.contains("<svg>"));
        assert!(filtered.contains("</svg>"));
    }
}
