//! MagiaMagica CLI — Rust 関数を魔法陣として描画する (Phase 1.7, M7 / Phase 2.1)。
//!
//! サブコマンド:
//! - `magia render <FILE> --fn <NAME>` — SVG を出力
//! - `magia list <FILE>` — 関数一覧
//! - `magia emit-ir <FILE> --fn <NAME>` — MagiaIR を JSON で出力 (デバッグ用)
//! - `magia serve <FILE> --fn <NAME>` — dev-server (保存のたびにブラウザを自動更新)
//! - `magia transcribe <FILE> --fn <NAME>` — 呪文書き起こし (アクセシビリティ用テキスト)
//! - `magia diff <BEFORE> <AFTER> --fn <NAME>` — 同一関数の2リビジョンの構造差分 (Spell Diff)。
//!   `--svg` で差分を強調した魔法陣を出力する

mod gitio;
mod serve;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

use magia_core::filter::{FilterSpec, LayerName};
use magia_core::layout::layout;
use magia_core::render::{RenderStyle, render_with};
use magia_rust::{list_functions, parse_function};

#[derive(Parser)]
#[command(name = "magia", version, about = "コードを魔法陣として描画する装置")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Rust 関数をミッドチルダ式の魔法陣 SVG として描画する
    Render {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 描画する関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// 描画するレイヤー (カンマ区切り)。省略時は全レイヤー
        #[arg(
            long,
            value_delimiter = ',',
            value_name = "LAYERS",
            conflicts_with = "filter"
        )]
        layers: Option<Vec<String>>,
        /// フィルター定義 (.magia) ファイル (spec v0.2 §8)
        #[arg(long, value_name = "FILE.magia")]
        filter: Option<PathBuf>,
        /// 出力先 SVG パス。省略時は標準出力
        #[arg(short, long, value_name = "OUT.svg")]
        output: Option<PathBuf>,
    },
    /// ファイル内の関数一覧を表示する
    List {
        /// 入力 Rust ソースファイル
        file: PathBuf,
    },
    /// MagiaIR を JSON で標準出力する (デバッグ用)
    #[command(name = "emit-ir")]
    EmitIr {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 対象の関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
    },
    /// 呪文書き起こし (構造のテキスト要約) を標準出力する
    Transcribe {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 対象の関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
    },
    /// 同一関数の2リビジョンを構造比較する — Spell Diff (spec v0.3 §9.2)
    Diff {
        /// 変更前の Rust ソースファイル (--git 指定時は比較対象ファイル)
        before: PathBuf,
        /// 変更後の Rust ソースファイル (--git 指定時は不要)
        after: Option<PathBuf>,
        /// git リビジョン比較モード: <REV> 時点の同ファイルを変更前として使う
        #[arg(long, value_name = "REV", conflicts_with = "after")]
        git: Option<String>,
        /// 比較する関数名 (両リビジョンに存在すること)
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// JSON で出力する (CI 連携用)
        #[arg(long, conflicts_with = "svg")]
        json: bool,
        /// 差分を強調した魔法陣 SVG を出力する (spec v0.3 §8 の overlay-diff)
        #[arg(long)]
        svg: bool,
        /// SVG のレイヤー絞り込み (.magia)。highlight: changed もここでは有効
        #[arg(long, value_name = "FILE.magia", requires = "svg")]
        filter: Option<PathBuf>,
        /// 出力先 SVG パス。省略時は標準出力 (--svg 指定時のみ有効)
        #[arg(short, long, value_name = "OUT.svg", requires = "svg")]
        output: Option<PathBuf>,
    },
    /// リビジョン以降に変更された関数を列挙する — CI の変更検出 (spec v0.3 §9.1)
    Changed {
        /// 比較基準のリビジョン (例: origin/main)
        #[arg(long, value_name = "REV")]
        git: String,
        /// JSON で出力する (CI 連携用)
        #[arg(long)]
        json: bool,
        /// unsafe 操作が新規追加された関数があれば exit 1 (spec v0.3 §9.3 の唯一の fail 条件)
        #[arg(long)]
        fail_on_new_unsafe: bool,
    },
    /// dev-server を起動する (ファイル保存のたびにブラウザの魔法陣を自動更新)
    Serve {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 描画する関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// 待ち受けポート (0 で空きポートを自動割当)
        #[arg(long, default_value_t = 4747)]
        port: u16,
    },
}

fn main() {
    if let Err(error) = run(Cli::parse()) {
        eprintln!("エラー: {error:#}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<()> {
    match cli.command {
        Command::Render {
            file,
            fn_name,
            layers,
            filter,
            output,
        } => {
            let spec = build_filter(layers.as_deref(), filter.as_deref())?;
            // highlight: changed は diff 文脈専用 (spec v0.3 §8)。黙って無視しない。
            if spec.highlight_changed {
                anyhow::bail!(
                    "highlight: changed には diff 文脈がありません (magia diff --svg で使用してください)"
                );
            }
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let placed = layout(&graph);
            let svg = render_with(&graph, &placed, RenderStyle::MidchildaConcentric, &spec);
            let svg = format!(
                "<!-- generated by magia-cli v{} -->\n{svg}",
                env!("CARGO_PKG_VERSION")
            );
            match output {
                Some(path) => fs::write(&path, svg)
                    .with_context(|| format!("SVG を書き出せません: {}", path.display()))?,
                None => print!("{svg}"),
            }
            Ok(())
        }
        Command::List { file } => {
            let source = read_source(&file)?;
            let names = list_functions(&source).map_err(|e| prettify_parse_error(&e))?;
            if names.is_empty() {
                eprintln!("関数が見つかりませんでした");
            }
            for name in names {
                println!("{name}");
            }
            Ok(())
        }
        Command::EmitIr { file, fn_name } => {
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let json =
                serde_json::to_string_pretty(&graph).context("IR の JSON 変換に失敗しました")?;
            println!("{json}");
            Ok(())
        }
        Command::Transcribe { file, fn_name } => {
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            print!("{}", magia_core::transcript::transcribe(&graph));
            Ok(())
        }
        Command::Diff {
            before,
            after,
            git,
            fn_name,
            json,
            svg,
            filter,
            output,
        } => {
            let sources = diff_sources(&before, after.as_deref(), git.as_deref())?;
            run_diff(
                &sources,
                &fn_name,
                json,
                svg,
                filter.as_deref(),
                output.as_deref(),
            )
        }
        Command::Changed {
            git,
            json,
            fail_on_new_unsafe,
        } => run_changed(&git, json, fail_on_new_unsafe),
        Command::Serve {
            file,
            fn_name,
            port,
        } => {
            // serve は起動時にファイルが読めなくても立ち上がり、画面にエラーを出す
            // (会話を切らない方針)。拡張子警告だけはここで出す。
            if file.extension().and_then(|e| e.to_str()) != Some("rs") {
                eprintln!(
                    "警告: `{}` は .rs ファイルではありません (Phase 1 の解析対象は Rust のみ)",
                    file.display()
                );
            }
            serve::run(&file, &fn_name, port)
        }
    }
}

fn read_source(path: &Path) -> Result<String> {
    if path.extension().and_then(|e| e.to_str()) != Some("rs") {
        // Phase 1 の解析対象は Rust のみ。間違いの早期発見のため警告する (続行はする)。
        eprintln!(
            "警告: `{}` は .rs ファイルではありません (Phase 1 の解析対象は Rust のみ)",
            path.display()
        );
    }
    fs::read_to_string(path)
        .with_context(|| format!("ファイルを読み込めません: {}", path.display()))
}

fn parse_source(source: &str, fn_name: &str) -> Result<magia_core::ir::MagiaGraph> {
    parse_function(source, fn_name).map_err(|e| prettify_parse_error(&e))
}

/// `magia-rust` のエラーをユーザー向けの日本語メッセージに整える。
/// 構文エラーは syn の span から行・列を取り出して付加する
/// (`Display` 単体ではメッセージしか出ない)。
fn prettify_parse_error(error: &magia_rust::Error) -> anyhow::Error {
    match error {
        magia_rust::Error::Syntax(syntax) => {
            let start = syntax.span().start();
            anyhow::anyhow!(
                "{error} ({}行目 {}文字目付近)",
                start.line,
                start.column + 1
            )
        }
        magia_rust::Error::FunctionNotFound { .. } => anyhow::anyhow!("{error}"),
    }
}

/// diff の入力2系統 (ファイル2つ / --git <REV>) を「ソース文字列ペア」に正規化する。
/// run_diff 以降は入力の出自を意識しない (複雑性をここで畳む)。
struct DiffSources {
    before_source: String,
    /// エラー表示用のラベル (例: "origin/main:src/lib.rs")
    before_label: String,
    after_source: String,
    after_label: String,
}

fn diff_sources(before: &Path, after: Option<&Path>, git: Option<&str>) -> Result<DiffSources> {
    match (after, git) {
        (Some(after), None) => Ok(DiffSources {
            before_source: read_source(before)?,
            before_label: before.display().to_string(),
            after_source: read_source(after)?,
            after_label: after.display().to_string(),
        }),
        // --git モード: <REV> 時点の同ファイルが変更前、作業ツリーが変更後。
        (None, Some(rev)) => Ok(DiffSources {
            before_source: gitio::show_file_at(rev, before)?,
            before_label: format!("{rev}:{}", before.display()),
            after_source: read_source(before)?,
            after_label: before.display().to_string(),
        }),
        (None, None) => anyhow::bail!(
            "変更後ファイルか --git <REV> のどちらかを指定してください (magia diff --help)"
        ),
        // clap の conflicts_with で弾かれるが、防御として明示する。
        (Some(_), Some(_)) => anyhow::bail!("<AFTER> と --git は同時に指定できません"),
    }
}

/// `magia diff` の本体。テキスト / JSON / 強調 SVG の3形態で出力する。
fn run_diff(
    sources: &DiffSources,
    fn_name: &str,
    json: bool,
    svg: bool,
    filter: Option<&Path>,
    output: Option<&Path>,
) -> Result<()> {
    let before_graph = parse_source(&sources.before_source, fn_name)
        .with_context(|| format!("変更前 ({})", sources.before_label))?;
    let after_graph = parse_source(&sources.after_source, fn_name)
        .with_context(|| format!("変更後 ({})", sources.after_label))?;
    let spell_diff = magia_core::diff::diff(&before_graph, &after_graph);
    if svg {
        // diff 文脈なので highlight: changed を含むフィルターも有効 (spec v0.3 §8)。
        let spec = build_filter(None, filter)?;
        let svg_text = magia_core::render::render_diff(
            &before_graph,
            &after_graph,
            &spell_diff,
            RenderStyle::MidchildaConcentric,
            &spec,
        );
        let svg_text = format!(
            "<!-- generated by magia-cli v{} -->\n{svg_text}",
            env!("CARGO_PKG_VERSION")
        );
        match output {
            Some(path) => fs::write(path, svg_text)
                .with_context(|| format!("SVG を書き出せません: {}", path.display()))?,
            None => print!("{svg_text}"),
        }
    } else if json {
        println!("{}", diff_to_json(&spell_diff, fn_name)?);
    } else {
        print!("{}", spell_diff.to_report(fn_name));
    }
    Ok(())
}

/// 変更関数1件の検出結果。
struct ChangedFunction {
    file: String,
    function: String,
    /// "追加" / "削除" / "変更"
    status: &'static str,
    /// unsafe 操作が新規に増えたか (spec v0.3 §9.3 の fail 条件)。
    new_unsafe: bool,
}

/// `magia changed --git <REV>` の本体。
///
/// 変更された .rs ファイルを git に聞き、各ファイルの関数一覧を before/after で
/// 突き合わせて「追加 / 削除 / 変更」を列挙する。構造が不変の関数は出さない。
/// 構文エラー等で解析できないファイルは警告して飛ばす (CI を解析失敗で
/// 落とさない — ビルドの成否は別ジョブの責務)。
fn run_changed(rev: &str, json: bool, fail_on_new_unsafe: bool) -> Result<()> {
    let cwd = Path::new(".");
    let root = gitio::repo_root(cwd)?;
    let mut entries: Vec<ChangedFunction> = Vec::new();

    for relative in gitio::changed_rs_files(rev, cwd)? {
        // 追加ファイルは before が、削除ファイルは after が None になる。
        let before_source = gitio::show_repo_file(rev, cwd, &relative).ok();
        let after_source = fs::read_to_string(root.join(&relative)).ok();
        let before_fns = functions_or_warn(before_source.as_deref(), rev, &relative);
        let after_fns = functions_or_warn(after_source.as_deref(), "作業ツリー", &relative);
        let before_set: std::collections::BTreeSet<&str> =
            before_fns.iter().map(String::as_str).collect();
        let after_set: std::collections::BTreeSet<&str> =
            after_fns.iter().map(String::as_str).collect();

        // after の出現順を基準にし、削除された関数を後ろに足す (決定論的)。
        for name in &after_fns {
            if before_set.contains(name.as_str()) {
                let (Some(before_src), Some(after_src)) =
                    (before_source.as_deref(), after_source.as_deref())
                else {
                    continue;
                };
                let (Ok(before_graph), Ok(after_graph)) = (
                    parse_function(before_src, name),
                    parse_function(after_src, name),
                ) else {
                    // 一覧には載るが個別解析に失敗 (マクロ境界等)。黙って不変扱いに
                    // しない — 警告して人間の確認に委ねる。
                    eprintln!(
                        "警告: {relative} の {name} を個別解析できないため diff を判定できません"
                    );
                    continue;
                };
                let spell_diff = magia_core::diff::diff(&before_graph, &after_graph);
                if spell_diff.is_empty() {
                    continue; // 不変の関数は列挙しない (spec §9.1: 変更された関数だけ)
                }
                entries.push(ChangedFunction {
                    file: relative.clone(),
                    function: name.clone(),
                    status: "変更",
                    new_unsafe: spell_diff.metrics.after.unsafe_ops
                        > spell_diff.metrics.before.unsafe_ops,
                });
            } else {
                let new_unsafe = after_source
                    .as_deref()
                    .and_then(|src| parse_function(src, name).ok())
                    .and_then(|graph| graph.modules.first().map(magia_core::metrics::measure))
                    .is_some_and(|m| m.unsafe_ops > 0);
                entries.push(ChangedFunction {
                    file: relative.clone(),
                    function: name.clone(),
                    status: "追加",
                    new_unsafe,
                });
            }
        }
        for name in &before_fns {
            if !after_set.contains(name.as_str()) {
                entries.push(ChangedFunction {
                    file: relative.clone(),
                    function: name.clone(),
                    status: "削除",
                    new_unsafe: false,
                });
            }
        }
    }

    print_changed(&entries, json)?;

    if fail_on_new_unsafe {
        let violations: Vec<String> = entries
            .iter()
            .filter(|e| e.new_unsafe)
            .map(|e| format!("{} の {}", e.file, e.function))
            .collect();
        if !violations.is_empty() {
            anyhow::bail!(
                "unsafe 操作が新規追加されています (spec v0.3 §9.3): {}",
                violations.join("、")
            );
        }
    }
    Ok(())
}

/// changed の検出結果をテキスト (TSV) または JSON で出力する。
fn print_changed(entries: &[ChangedFunction], json: bool) -> Result<()> {
    if json {
        let value = entries
            .iter()
            .map(|e| {
                serde_json::json!({
                    "file": e.file,
                    "function": e.function,
                    "status": e.status,
                    "new_unsafe": e.new_unsafe,
                })
            })
            .collect::<Vec<_>>();
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::Value::Array(value))
                .context("changed の JSON 変換に失敗しました")?
        );
    } else {
        for entry in entries {
            let mark = if entry.new_unsafe {
                "\t⚠ unsafe 追加"
            } else {
                ""
            };
            println!(
                "{}\t{}\t{}{}",
                entry.file, entry.function, entry.status, mark
            );
        }
    }
    Ok(())
}

/// ソースから関数名一覧を取る。解析できなければ警告して空にする。
fn functions_or_warn(source: Option<&str>, revision: &str, file: &str) -> Vec<String> {
    let Some(source) = source else {
        return Vec::new();
    };
    match list_functions(source) {
        Ok(names) => names,
        Err(error) => {
            eprintln!("警告: {revision} の {file} を解析できません ({error})");
            Vec::new()
        }
    }
}

/// SpellDiff を CI 連携用の JSON に整形する。
/// IR と違い diff 型は Serialize を持たない (公開スキーマは CLI 出力だけに限定し、
/// core の内部表現を JSON 契約から切り離す) ため、ここで明示的に組み立てる。
fn diff_to_json(spell_diff: &magia_core::diff::SpellDiff, fn_name: &str) -> Result<String> {
    let metrics_json = |m: &magia_core::metrics::Metrics| {
        serde_json::json!({
            "complexity": m.complexity,
            "effect_categories": m.effect_categories,
            "rings": m.rings,
            "glyphs": m.glyphs,
            "early_returns": m.early_returns,
            "main_operations": m.main_operations,
            "unsafe_ops": m.unsafe_ops,
        })
    };
    let value = serde_json::json!({
        "function": fn_name,
        "is_empty": spell_diff.is_empty(),
        // 経路文字列のみを契約に出す。SigilId はリビジョン間で不安定 (spec §9.2) なので
        // 外部 (CI) に持ち出させない。
        "added": spell_diff.added.iter().map(|n| &n.path).collect::<Vec<_>>(),
        "removed": spell_diff.removed.iter().map(|n| &n.path).collect::<Vec<_>>(),
        "changed": spell_diff
            .changed
            .iter()
            .map(|c| serde_json::json!({ "path": c.path, "details": c.details }))
            .collect::<Vec<_>>(),
        "metrics": {
            "before": metrics_json(&spell_diff.metrics.before),
            "after": metrics_json(&spell_diff.metrics.after),
        },
    });
    serde_json::to_string_pretty(&value).context("diff の JSON 変換に失敗しました")
}

/// `--layers` (show 単独の糖衣) と `--filter <FILE.magia>` から FilterSpec を作る。
/// 両方の同時指定は clap の `conflicts_with` で拒否される。
/// レイヤー単位の出力ゲートは render 側 (spec v0.2 §8) が行う。
fn build_filter(layers: Option<&[String]>, filter_file: Option<&Path>) -> Result<FilterSpec> {
    if let Some(path) = filter_file {
        let text = fs::read_to_string(path)
            .with_context(|| format!("フィルターを読み込めません: {}", path.display()))?;
        return FilterSpec::parse(&text).map_err(|e| anyhow::anyhow!("{}: {e}", path.display()));
    }
    let Some(layers) = layers else {
        return Ok(FilterSpec::default());
    };
    let mut selected = Vec::new();
    for name in layers {
        let layer: LayerName = name.parse().map_err(|message: String| {
            anyhow::anyhow!("{message}") // 候補一覧つきメッセージは LayerName 側が持つ
        })?;
        selected.push(layer);
    }
    Ok(FilterSpec::show_only(selected))
}

#[cfg(test)]
mod tests {
    use super::*;
    use magia_core::filter::EffectCategory;

    #[test]
    fn build_filter_accepts_known_layer_names() {
        let layers = vec!["control_flow".to_string(), "effects".to_string()];
        let spec = build_filter(Some(&layers), None).unwrap();
        assert!(spec.is_visible(LayerName::ControlFlow));
        assert!(spec.is_visible(LayerName::Effects));
        assert!(!spec.is_visible(LayerName::TypeInfo));
    }

    #[test]
    fn build_filter_rejects_unknown_name_with_candidates() {
        let layers = vec!["controlflow".to_string()];
        let error = build_filter(Some(&layers), None).unwrap_err();
        assert!(error.to_string().contains("未知のレイヤー名"));
        assert!(error.to_string().contains("control_flow"));
    }

    #[test]
    fn build_filter_reads_magia_file() {
        let dir = std::env::temp_dir().join("magia-cli-filter-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("ok.magia");
        std::fs::write(&path, "show: effects[io]\n").unwrap();
        let spec = build_filter(None, Some(&path)).unwrap();
        assert!(!spec.is_visible(LayerName::ControlFlow));
        assert_eq!(
            spec.effect_categories(),
            Some([EffectCategory::Io].as_slice())
        );
    }

    #[test]
    fn build_filter_reports_parse_error_with_file_and_line() {
        let dir = std::env::temp_dir().join("magia-cli-filter-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bad.magia");
        std::fs::write(&path, "# c\nshow: nope\n").unwrap();
        let error = build_filter(None, Some(&path)).unwrap_err();
        let message = error.to_string();
        assert!(message.contains("bad.magia") && message.contains("2行目"));
    }
}
