//! MagiaMagica CLI — Rust 関数を魔法陣として描画する (Phase 1.7, M7 / Phase 2.1)。
//!
//! サブコマンド:
//! - `magia render <FILE> --fn <NAME>` — SVG を出力
//! - `magia list <FILE>` — 関数一覧
//! - `magia emit-ir <FILE> --fn <NAME>` — MagiaIR を JSON で出力 (デバッグ用)
//! - `magia serve <FILE> --fn <NAME>` — dev-server (保存のたびにブラウザを自動更新)

mod serve;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

use magia_core::filter::{FilterSpec, LayerName};
use magia_core::layout::layout;
use magia_core::render::{RenderStyle, render_with};
use magia_rust::{list_functions, parse_function};

#[derive(Parser)]
#[command(name = "magia", version, about = "コードを魔法陣として描画する装置")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Rust 関数をミッドチルダ式の魔法陣 SVG として描画する
    Render {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 描画する関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// 描画するレイヤー (カンマ区切り)。省略時は全レイヤー
        #[arg(
            long,
            value_delimiter = ',',
            value_name = "LAYERS",
            conflicts_with = "filter"
        )]
        layers: Option<Vec<String>>,
        /// フィルター定義 (.magia) ファイル (spec v0.2 §8)
        #[arg(long, value_name = "FILE.magia")]
        filter: Option<PathBuf>,
        /// 出力先 SVG パス。省略時は標準出力
        #[arg(short, long, value_name = "OUT.svg")]
        output: Option<PathBuf>,
    },
    /// ファイル内の関数一覧を表示する
    List {
        /// 入力 Rust ソースファイル
        file: PathBuf,
    },
    /// MagiaIR を JSON で標準出力する (デバッグ用)
    #[command(name = "emit-ir")]
    EmitIr {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 対象の関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
    },
    /// dev-server を起動する (ファイル保存のたびにブラウザの魔法陣を自動更新)
    Serve {
        /// 入力 Rust ソースファイル
        file: PathBuf,
        /// 描画する関数名
        #[arg(long = "fn", value_name = "NAME")]
        fn_name: String,
        /// 待ち受けポート (0 で空きポートを自動割当)
        #[arg(long, default_value_t = 4747)]
        port: u16,
    },
}

fn main() {
    if let Err(error) = run(Cli::parse()) {
        eprintln!("エラー: {error:#}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<()> {
    match cli.command {
        Command::Render {
            file,
            fn_name,
            layers,
            filter,
            output,
        } => {
            let spec = build_filter(layers.as_deref(), filter.as_deref())?;
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let placed = layout(&graph);
            let svg = render_with(&graph, &placed, RenderStyle::MidchildaConcentric, &spec);
            let svg = format!(
                "<!-- generated by magia-cli v{} -->\n{svg}",
                env!("CARGO_PKG_VERSION")
            );
            match output {
                Some(path) => fs::write(&path, svg)
                    .with_context(|| format!("SVG を書き出せません: {}", path.display()))?,
                None => print!("{svg}"),
            }
            Ok(())
        }
        Command::List { file } => {
            let source = read_source(&file)?;
            let names = list_functions(&source).map_err(|e| prettify_parse_error(&e))?;
            if names.is_empty() {
                eprintln!("関数が見つかりませんでした");
            }
            for name in names {
                println!("{name}");
            }
            Ok(())
        }
        Command::EmitIr { file, fn_name } => {
            let source = read_source(&file)?;
            let graph = parse_source(&source, &fn_name)?;
            let json =
                serde_json::to_string_pretty(&graph).context("IR の JSON 変換に失敗しました")?;
            println!("{json}");
            Ok(())
        }
        Command::Serve {
            file,
            fn_name,
            port,
        } => {
            // serve は起動時にファイルが読めなくても立ち上がり、画面にエラーを出す
            // (会話を切らない方針)。拡張子警告だけはここで出す。
            if file.extension().and_then(|e| e.to_str()) != Some("rs") {
                eprintln!(
                    "警告: `{}` は .rs ファイルではありません (Phase 1 の解析対象は Rust のみ)",
                    file.display()
                );
            }
            serve::run(&file, &fn_name, port)
        }
    }
}

fn read_source(path: &Path) -> Result<String> {
    if path.extension().and_then(|e| e.to_str()) != Some("rs") {
        // Phase 1 の解析対象は Rust のみ。間違いの早期発見のため警告する (続行はする)。
        eprintln!(
            "警告: `{}` は .rs ファイルではありません (Phase 1 の解析対象は Rust のみ)",
            path.display()
        );
    }
    fs::read_to_string(path)
        .with_context(|| format!("ファイルを読み込めません: {}", path.display()))
}

fn parse_source(source: &str, fn_name: &str) -> Result<magia_core::ir::MagiaGraph> {
    parse_function(source, fn_name).map_err(|e| prettify_parse_error(&e))
}

/// `magia-rust` のエラーをユーザー向けの日本語メッセージに整える。
/// 構文エラーは syn の span から行・列を取り出して付加する
/// (`Display` 単体ではメッセージしか出ない)。
fn prettify_parse_error(error: &magia_rust::Error) -> anyhow::Error {
    match error {
        magia_rust::Error::Syntax(syntax) => {
            let start = syntax.span().start();
            anyhow::anyhow!(
                "{error} ({}行目 {}文字目付近)",
                start.line,
                start.column + 1
            )
        }
        magia_rust::Error::FunctionNotFound { .. } => anyhow::anyhow!("{error}"),
    }
}

/// `--layers` (show 単独の糖衣) と `--filter <FILE.magia>` から FilterSpec を作る。
/// 両方の同時指定は clap の `conflicts_with` で拒否される。
/// レイヤー単位の出力ゲートは render 側 (spec v0.2 §8) が行う。
fn build_filter(layers: Option<&[String]>, filter_file: Option<&Path>) -> Result<FilterSpec> {
    if let Some(path) = filter_file {
        let text = fs::read_to_string(path)
            .with_context(|| format!("フィルターを読み込めません: {}", path.display()))?;
        return FilterSpec::parse(&text).map_err(|e| anyhow::anyhow!("{}: {e}", path.display()));
    }
    let Some(layers) = layers else {
        return Ok(FilterSpec::default());
    };
    let mut selected = Vec::new();
    for name in layers {
        let layer: LayerName = name.parse().map_err(|message: String| {
            anyhow::anyhow!("{message}") // 候補一覧つきメッセージは LayerName 側が持つ
        })?;
        selected.push(layer);
    }
    Ok(FilterSpec::show_only(selected))
}

#[cfg(test)]
mod tests {
    use super::*;
    use magia_core::filter::EffectCategory;

    #[test]
    fn build_filter_accepts_known_layer_names() {
        let layers = vec!["control_flow".to_string(), "effects".to_string()];
        let spec = build_filter(Some(&layers), None).unwrap();
        assert!(spec.is_visible(LayerName::ControlFlow));
        assert!(spec.is_visible(LayerName::Effects));
        assert!(!spec.is_visible(LayerName::TypeInfo));
    }

    #[test]
    fn build_filter_rejects_unknown_name_with_candidates() {
        let layers = vec!["controlflow".to_string()];
        let error = build_filter(Some(&layers), None).unwrap_err();
        assert!(error.to_string().contains("未知のレイヤー名"));
        assert!(error.to_string().contains("control_flow"));
    }

    #[test]
    fn build_filter_reads_magia_file() {
        let dir = std::env::temp_dir().join("magia-cli-filter-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("ok.magia");
        std::fs::write(&path, "show: effects[io]\n").unwrap();
        let spec = build_filter(None, Some(&path)).unwrap();
        assert!(!spec.is_visible(LayerName::ControlFlow));
        assert_eq!(
            spec.effect_categories(),
            Some([EffectCategory::Io].as_slice())
        );
    }

    #[test]
    fn build_filter_reports_parse_error_with_file_and_line() {
        let dir = std::env::temp_dir().join("magia-cli-filter-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bad.magia");
        std::fs::write(&path, "# c\nshow: nope\n").unwrap();
        let error = build_filter(None, Some(&path)).unwrap_err();
        let message = error.to_string();
        assert!(message.contains("bad.magia") && message.contains("2行目"));
    }
}
