//! CLI 統合テスト (Phase 1.7 受け入れ基準)。
//!
//! ワークスペースルートの `fixtures/` を実データとして `magia` バイナリを起動する。

use std::path::PathBuf;
use std::process::Command;

use assert_cmd::prelude::*;

/// ワークスペースルートの fixtures ディレクトリ。
/// 統合テストの CWD はクレートルート (`crates/magia-cli`) なので2段上がる。
fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
}

fn magia() -> Command {
    Command::cargo_bin("magia").expect("magia バイナリがビルドされている")
}

/// fixture ファイル名 → 代表関数名 (ファイル名と同名の関数を置く規約)。
const FIXTURES: &[&str] = &[
    "simple_compute",
    "io_print",
    "network_fetch",
    "db_query",
    "filesystem_read",
    "unsafe_ptr",
    "async_await",
    "result_chain",
    "match_dispatch",
    "loop_accumulate",
];

#[test]
fn render_succeeds_for_every_fixture() {
    for name in FIXTURES {
        let output = magia()
            .arg("render")
            .arg(fixtures_dir().join(format!("{name}.rs")))
            .arg("--fn")
            .arg(name)
            .output()
            .expect("CLI を起動できる");
        assert!(
            output.status.success(),
            "{name} の render が失敗: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let svg = String::from_utf8_lossy(&output.stdout);
        assert!(svg.starts_with("<!-- generated by magia-cli v"));
        assert!(svg.contains("<svg "), "{name}: SVG ルート要素がある");
        assert!(svg.trim_end().ends_with("</svg>"));
    }
}

#[test]
fn list_enumerates_all_functions() {
    let output = magia()
        .arg("list")
        .arg(fixtures_dir().join("match_dispatch.rs"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.lines().any(|l| l == "match_dispatch"));
}

#[test]
fn missing_function_error_lists_candidates() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("no_such_fn")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("no_such_fn"), "未発見の関数名が出る");
    assert!(
        stderr.contains("simple_compute"),
        "候補一覧が出る: {stderr}"
    );
}

#[test]
fn syntax_error_reports_line_number() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken.rs");
    std::fs::write(&path, "fn broken( {\n").unwrap();
    let output = magia()
        .arg("list")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("構文エラー"));
    assert!(stderr.contains("行目"), "行番号が出る: {stderr}");
}

#[test]
fn render_syntax_error_also_reports_line_number() {
    // list と render は同じ prettify_parse_error を通る。render 経路も保証する。
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken2.rs");
    std::fs::write(&path, "\n\nfn broken( {\n").unwrap();
    let output = magia()
        .arg("render")
        .arg(&path)
        .arg("--fn")
        .arg("broken")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("構文エラー") && stderr.contains("行目"));
}

#[test]
fn non_rs_extension_warns_but_continues() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("sample.txt");
    std::fs::write(&path, "fn from_txt() {}\n").unwrap();
    let output = magia()
        .arg("list")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success(), "警告のみで処理は続行する");
    assert!(String::from_utf8_lossy(&output.stderr).contains("警告"));
    assert!(String::from_utf8_lossy(&output.stdout).contains("from_txt"));
}

#[test]
fn layers_option_filters_groups() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("effects")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains(r#"<g class="layer-effects">"#));
    assert!(!svg.contains(r#"<g class="layer-control-flow">"#));
    assert!(!svg.contains(r#"<g class="layer-type-info">"#));
}

#[test]
fn unknown_layer_name_is_rejected() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("efects")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("未知のレイヤー名"));
}

#[test]
fn filter_file_shows_only_selected_layer() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/effects-only.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains(r#"<g class="layer-effects">"#));
    assert!(!svg.contains(r#"<g class="layer-control-flow">"#));
    assert!(!svg.contains(r#"<g class="layer-type-info">"#));
}

#[test]
fn filter_effect_categories_drop_other_symbols() {
    // db_query は rusqlite (db/緑) + 未知 helper (pure/黒) を呼ぶ。
    // effects[network, db] では pure の記号が消え、db の緑だけ残る。
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("db_query.rs"))
        .arg("--fn")
        .arg("db_query")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/network-db.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains("#1fa341"), "db の緑が残る");
    // pure カテゴリの記号 (op-dot / summon-glyph) だけが消えることを確認する。
    // control_flow 層の黒 (ループ矢印等) は対象外なので、effects 層の要素に絞って見る。
    assert!(
        !svg.lines().any(
            |line| (line.contains("op-dot") || line.contains("summon-glyph"))
                && line.contains("#000000")
        ),
        "effects 層に pure (黒) の記号が残っていない"
    );
}

#[test]
fn filter_and_layers_conflict() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("effects")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/effects-only.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(
        !output.status.success(),
        "--layers と --filter は同時指定不可"
    );
}

#[test]
fn broken_filter_file_reports_line() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken.magia");
    std::fs::write(&path, "show: effects\nshow: nope\n").unwrap();
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--filter")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("2行目") && stderr.contains("未知のレイヤー名"));
}

#[test]
fn emit_ir_outputs_valid_json() {
    let output = magia()
        .arg("emit-ir")
        .arg(fixtures_dir().join("result_chain.rs"))
        .arg("--fn")
        .arg("result_chain")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let json: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("emit-ir は有効な JSON を出す");
    let modules = json["modules"].as_array().expect("modules は配列");
    assert!(!modules.is_empty());
    assert!(
        modules[0]["sigils"]
            .as_array()
            .is_some_and(|s| !s.is_empty()),
        "MainRing を含む sigils が入っている"
    );
}

#[test]
fn output_flag_writes_svg_file() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let out = dir.join("simple_compute.svg");
    magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("simple_compute")
        .arg("-o")
        .arg(&out)
        .assert()
        .success();
    let svg = std::fs::read_to_string(&out).expect("出力ファイルが存在する");
    assert!(svg.contains("</svg>"));
}

#[test]
fn transcribe_outputs_summary() {
    let output = magia()
        .arg("transcribe")
        .arg(fixtures_dir().join("async_await.rs"))
        .arg("--fn")
        .arg("async_await")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("関数 async_await:"));
    assert!(text.contains("async 関数 (await 2点)。"));
}

#[test]
fn diff_reports_structural_changes_as_text() {
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/after.rs"))
        .arg("--fn")
        .arg("process_order")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("SpellDiff (関数 process_order):"));
    assert!(text.contains("追加: main > else分岐"));
    assert!(text.contains("削除: main > 召喚 notify"));
    assert!(text.contains("メトリクス変化"));
}

#[test]
fn diff_json_is_valid_and_carries_metrics() {
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/after.rs"))
        .arg("--fn")
        .arg("process_order")
        .arg("--json")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let json: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("diff --json は有効な JSON を出す");
    assert_eq!(json["function"], "process_order");
    assert_eq!(json["is_empty"], false);
    assert!(json["added"].as_array().is_some_and(|a| !a.is_empty()));
    assert_eq!(json["metrics"]["before"]["rings"], 3);
    assert_eq!(json["metrics"]["after"]["rings"], 4);
}

#[test]
fn diff_of_identical_files_is_empty() {
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg("--fn")
        .arg("process_order")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("構造の変化なし"));
}

#[test]
fn diff_svg_writes_overlay_channel() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let out = dir.join("diff_overlay.svg");
    magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/after.rs"))
        .arg("--fn")
        .arg("process_order")
        .arg("--svg")
        .arg("-o")
        .arg(&out)
        .assert()
        .success();
    let svg = std::fs::read_to_string(&out).expect("出力ファイルが存在する");
    assert!(svg.contains(r#"<g class="overlay-diff">"#));
    assert!(svg.contains("diff-added") && svg.contains("diff-removed"));
    assert!(svg.contains("</svg>"));
}

#[test]
fn diff_svg_accepts_highlight_changed_filter() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let filter = dir.join("highlight.magia");
    std::fs::write(&filter, "show: control_flow\nhighlight: changed\n").unwrap();
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/after.rs"))
        .arg("--fn")
        .arg("process_order")
        .arg("--svg")
        .arg("--filter")
        .arg(&filter)
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(
        svg.contains("overlay-diff"),
        "diff 文脈では highlight: changed が機能する"
    );
}

#[test]
fn render_rejects_highlight_without_diff_context() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let filter = dir.join("highlight-only.magia");
    std::fs::write(&filter, "highlight: changed\n").unwrap();
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("simple_compute")
        .arg("--filter")
        .arg(&filter)
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("diff 文脈がありません"));
    assert!(
        stderr.contains("magia diff --svg"),
        "使うべきコマンドを案内する"
    );
}

#[test]
fn diff_svg_conflicts_with_json() {
    magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("diff/after.rs"))
        .arg("--fn")
        .arg("process_order")
        .arg("--svg")
        .arg("--json")
        .assert()
        .failure();
}

#[test]
fn diff_missing_function_names_the_offending_file() {
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("process_order")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    // どちら側のファイルで関数が見つからなかったかを案内する。
    assert!(stderr.contains("変更後") && stderr.contains("simple_compute.rs"));
}

// ===== Phase 3.3: git 連携 (--git / changed) =====

/// 一時 git リポジトリを作り、v1 をコミット → v2 を作業ツリーに置く。
/// v1→v2 の差分: alpha は extra() 呼び出しが増え (変更)、gone は消え (削除)、
/// fresh は unsafe fn として新規追加 (unsafe 新規追加の fail 条件を踏む)。
fn init_git_fixture(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("magia-git-test-{name}"));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    let git = |args: &[&str]| {
        let output = Command::new("git")
            .arg("-C")
            .arg(&dir)
            .args(args)
            .output()
            .expect("git を起動できる");
        assert!(
            output.status.success(),
            "git {args:?} が失敗: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    };
    git(&["init", "-q"]);
    git(&["config", "user.email", "test@example.com"]);
    git(&["config", "user.name", "test"]);
    std::fs::write(
        dir.join("sample.rs"),
        "fn alpha(x: u32) -> u32 { helper(x) }\nfn gone() {}\n",
    )
    .unwrap();
    git(&["add", "sample.rs"]);
    git(&["commit", "-q", "-m", "v1"]);
    std::fs::write(
        dir.join("sample.rs"),
        "fn alpha(x: u32) -> u32 { extra(x); helper(x) }\nunsafe fn fresh(p: *const u8) -> u8 { *p }\n",
    )
    .unwrap();
    dir
}

#[test]
fn diff_git_mode_compares_against_revision() {
    let dir = init_git_fixture("diff");
    let output = magia()
        .current_dir(&dir)
        .arg("diff")
        .arg("sample.rs")
        .arg("--git")
        .arg("HEAD")
        .arg("--fn")
        .arg("alpha")
        .output()
        .expect("CLI を起動できる");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("追加: main > 召喚 extra"));
}

#[test]
fn diff_requires_after_or_git() {
    let output = magia()
        .arg("diff")
        .arg(fixtures_dir().join("diff/before.rs"))
        .arg("--fn")
        .arg("process_order")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("--git"), "案内が出る: {stderr}");
}

#[test]
fn changed_lists_added_removed_and_modified_functions() {
    let dir = init_git_fixture("changed");
    let output = magia()
        .current_dir(&dir)
        .arg("changed")
        .arg("--git")
        .arg("HEAD")
        .output()
        .expect("CLI を起動できる");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("alpha\t変更"));
    assert!(text.contains("gone\t削除"));
    assert!(text.contains("fresh\t追加"));
    assert!(text.contains("unsafe 追加"), "unsafe の警告マークが出る");
}

#[test]
fn changed_json_carries_new_unsafe_flag() {
    let dir = init_git_fixture("changed-json");
    let output = magia()
        .current_dir(&dir)
        .arg("changed")
        .arg("--git")
        .arg("HEAD")
        .arg("--json")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let json: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("changed --json は有効な JSON を出す");
    let entries = json.as_array().expect("配列");
    let fresh = entries
        .iter()
        .find(|e| e["function"] == "fresh")
        .expect("fresh が列挙される");
    assert_eq!(fresh["status"], "追加");
    assert_eq!(fresh["new_unsafe"], true);
    let alpha = entries
        .iter()
        .find(|e| e["function"] == "alpha")
        .expect("alpha が列挙される");
    assert_eq!(alpha["new_unsafe"], false);
}

#[test]
fn changed_fails_on_new_unsafe_when_requested() {
    let dir = init_git_fixture("fail-unsafe");
    let output = magia()
        .current_dir(&dir)
        .arg("changed")
        .arg("--git")
        .arg("HEAD")
        .arg("--fail-on-new-unsafe")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success(), "unsafe 新規追加で fail する");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unsafe 操作が新規追加"));
    assert!(stderr.contains("fresh"), "違反した関数名が出る");
}

#[test]
fn changed_passes_when_no_new_unsafe() {
    let dir = init_git_fixture("pass-unsafe");
    // unsafe を含まない v2 に差し替える (alpha の変更のみ)。
    std::fs::write(
        dir.join("sample.rs"),
        "fn alpha(x: u32) -> u32 { extra(x); helper(x) }\nfn gone() {}\n",
    )
    .unwrap();
    magia()
        .current_dir(&dir)
        .arg("changed")
        .arg("--git")
        .arg("HEAD")
        .arg("--fail-on-new-unsafe")
        .assert()
        .success();
}

// ===== Phase 3.5: ベルカ式 (--style) =====

#[test]
fn render_style_belka_outputs_triangle_field() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("loop_accumulate.rs"))
        .arg("--fn")
        .arg("loop_accumulate")
        .arg("--style")
        .arg("belka")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains("belka-pole"));
    assert!(svg.contains("belka-field"));
    assert!(
        !svg.contains("layer-control-flow"),
        "ミッドチルダ式の層は出ない"
    );
}

#[test]
fn render_unknown_style_lists_candidates() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("simple_compute")
        .arg("--style")
        .arg("yagami")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success(), "夜天の書式は未実装 (選択不可)");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("未知の式"));
    assert!(
        stderr.contains("midchilda") && stderr.contains("belka"),
        "候補を提示する"
    );
}

#[test]
fn reducer_shape_prints_belka_hint() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("reduce_brightness.rs"))
        .arg("--fn")
        .arg("reduce_brightness")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("ベルカ式が適合します") && stderr.contains("--style belka"),
        "Reducer 形には式の提案が出る (spec v0.3 §14.3): {stderr}"
    );
    // 提案のみで自動切替はしない: 出力はミッドチルダ式のまま。
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains("layer-control-flow"));
}

#[test]
fn belka_hint_is_absent_for_non_reducer_and_when_already_belka() {
    // match_dispatch は u8 -> &'static str (非 Reducer 形)。
    // ※ simple_compute は (i32, i32) -> i32 で Reducer 形に該当するため使わない。
    let plain = magia()
        .arg("render")
        .arg(fixtures_dir().join("match_dispatch.rs"))
        .arg("--fn")
        .arg("match_dispatch")
        .output()
        .expect("CLI を起動できる");
    assert!(!String::from_utf8_lossy(&plain.stderr).contains("ベルカ式"));
    let belka = magia()
        .arg("render")
        .arg(fixtures_dir().join("reduce_brightness.rs"))
        .arg("--fn")
        .arg("reduce_brightness")
        .arg("--style")
        .arg("belka")
        .output()
        .expect("CLI を起動できる");
    assert!(
        !String::from_utf8_lossy(&belka.stderr).contains("適合します"),
        "既にベルカ式なら提案しない"
    );
}

#[test]
fn belka_rejects_filter_file_too() {
    // --layers と同じ経路だが、API のもう一方の入口 (--filter FILE) も明示的に検証する。
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("loop_accumulate.rs"))
        .arg("--fn")
        .arg("loop_accumulate")
        .arg("--style")
        .arg("belka")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/effects-only.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("未対応"));
}

#[test]
fn belka_rejects_layer_filters() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("loop_accumulate.rs"))
        .arg("--fn")
        .arg("loop_accumulate")
        .arg("--style")
        .arg("belka")
        .arg("--layers")
        .arg("effects")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success(), "ベルカ式はレイヤー語彙に未対応");
    assert!(String::from_utf8_lossy(&output.stderr).contains("未対応"));
}

#[test]
fn version_and_help_work() {
    magia().arg("--version").assert().success();
    magia().arg("--help").assert().success();
}
