//! CLI 統合テスト (Phase 1.7 受け入れ基準)。
//!
//! ワークスペースルートの `fixtures/` を実データとして `magia` バイナリを起動する。

use std::path::PathBuf;
use std::process::Command;

use assert_cmd::prelude::*;

/// ワークスペースルートの fixtures ディレクトリ。
/// 統合テストの CWD はクレートルート (`crates/magia-cli`) なので2段上がる。
fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
}

fn magia() -> Command {
    Command::cargo_bin("magia").expect("magia バイナリがビルドされている")
}

/// fixture ファイル名 → 代表関数名 (ファイル名と同名の関数を置く規約)。
const FIXTURES: &[&str] = &[
    "simple_compute",
    "io_print",
    "network_fetch",
    "db_query",
    "filesystem_read",
    "unsafe_ptr",
    "async_await",
    "result_chain",
    "match_dispatch",
    "loop_accumulate",
];

#[test]
fn render_succeeds_for_every_fixture() {
    for name in FIXTURES {
        let output = magia()
            .arg("render")
            .arg(fixtures_dir().join(format!("{name}.rs")))
            .arg("--fn")
            .arg(name)
            .output()
            .expect("CLI を起動できる");
        assert!(
            output.status.success(),
            "{name} の render が失敗: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let svg = String::from_utf8_lossy(&output.stdout);
        assert!(svg.starts_with("<!-- generated by magia-cli v"));
        assert!(svg.contains("<svg "), "{name}: SVG ルート要素がある");
        assert!(svg.trim_end().ends_with("</svg>"));
    }
}

#[test]
fn list_enumerates_all_functions() {
    let output = magia()
        .arg("list")
        .arg(fixtures_dir().join("match_dispatch.rs"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.lines().any(|l| l == "match_dispatch"));
}

#[test]
fn missing_function_error_lists_candidates() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("no_such_fn")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("no_such_fn"), "未発見の関数名が出る");
    assert!(
        stderr.contains("simple_compute"),
        "候補一覧が出る: {stderr}"
    );
}

#[test]
fn syntax_error_reports_line_number() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken.rs");
    std::fs::write(&path, "fn broken( {\n").unwrap();
    let output = magia()
        .arg("list")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("構文エラー"));
    assert!(stderr.contains("行目"), "行番号が出る: {stderr}");
}

#[test]
fn render_syntax_error_also_reports_line_number() {
    // list と render は同じ prettify_parse_error を通る。render 経路も保証する。
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken2.rs");
    std::fs::write(&path, "\n\nfn broken( {\n").unwrap();
    let output = magia()
        .arg("render")
        .arg(&path)
        .arg("--fn")
        .arg("broken")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("構文エラー") && stderr.contains("行目"));
}

#[test]
fn non_rs_extension_warns_but_continues() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("sample.txt");
    std::fs::write(&path, "fn from_txt() {}\n").unwrap();
    let output = magia()
        .arg("list")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success(), "警告のみで処理は続行する");
    assert!(String::from_utf8_lossy(&output.stderr).contains("警告"));
    assert!(String::from_utf8_lossy(&output.stdout).contains("from_txt"));
}

#[test]
fn layers_option_filters_groups() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("effects")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains(r#"<g class="layer-effects">"#));
    assert!(!svg.contains(r#"<g class="layer-control-flow">"#));
    assert!(!svg.contains(r#"<g class="layer-type-info">"#));
}

#[test]
fn unknown_layer_name_is_rejected() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("efects")
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("未知のレイヤー名"));
}

#[test]
fn filter_file_shows_only_selected_layer() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/effects-only.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains(r#"<g class="layer-effects">"#));
    assert!(!svg.contains(r#"<g class="layer-control-flow">"#));
    assert!(!svg.contains(r#"<g class="layer-type-info">"#));
}

#[test]
fn filter_effect_categories_drop_other_symbols() {
    // db_query は rusqlite (db/緑) + 未知 helper (pure/黒) を呼ぶ。
    // effects[network, db] では pure の記号が消え、db の緑だけ残る。
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("db_query.rs"))
        .arg("--fn")
        .arg("db_query")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/network-db.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let svg = String::from_utf8_lossy(&output.stdout);
    assert!(svg.contains("#1fa341"), "db の緑が残る");
    // pure カテゴリの記号 (op-dot / summon-glyph) だけが消えることを確認する。
    // control_flow 層の黒 (ループ矢印等) は対象外なので、effects 層の要素に絞って見る。
    assert!(
        !svg.lines().any(
            |line| (line.contains("op-dot") || line.contains("summon-glyph"))
                && line.contains("#000000")
        ),
        "effects 層に pure (黒) の記号が残っていない"
    );
}

#[test]
fn filter_and_layers_conflict() {
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--layers")
        .arg("effects")
        .arg("--filter")
        .arg(fixtures_dir().join("filters/effects-only.magia"))
        .output()
        .expect("CLI を起動できる");
    assert!(
        !output.status.success(),
        "--layers と --filter は同時指定不可"
    );
}

#[test]
fn broken_filter_file_reports_line() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("broken.magia");
    std::fs::write(&path, "show: effects\nshow: nope\n").unwrap();
    let output = magia()
        .arg("render")
        .arg(fixtures_dir().join("io_print.rs"))
        .arg("--fn")
        .arg("io_print")
        .arg("--filter")
        .arg(&path)
        .output()
        .expect("CLI を起動できる");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("2行目") && stderr.contains("未知のレイヤー名"));
}

#[test]
fn emit_ir_outputs_valid_json() {
    let output = magia()
        .arg("emit-ir")
        .arg(fixtures_dir().join("result_chain.rs"))
        .arg("--fn")
        .arg("result_chain")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let json: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("emit-ir は有効な JSON を出す");
    let modules = json["modules"].as_array().expect("modules は配列");
    assert!(!modules.is_empty());
    assert!(
        modules[0]["sigils"]
            .as_array()
            .is_some_and(|s| !s.is_empty()),
        "MainRing を含む sigils が入っている"
    );
}

#[test]
fn output_flag_writes_svg_file() {
    let dir = std::env::temp_dir().join("magia-cli-test");
    std::fs::create_dir_all(&dir).unwrap();
    let out = dir.join("simple_compute.svg");
    magia()
        .arg("render")
        .arg(fixtures_dir().join("simple_compute.rs"))
        .arg("--fn")
        .arg("simple_compute")
        .arg("-o")
        .arg(&out)
        .assert()
        .success();
    let svg = std::fs::read_to_string(&out).expect("出力ファイルが存在する");
    assert!(svg.contains("</svg>"));
}

#[test]
fn transcribe_outputs_summary() {
    let output = magia()
        .arg("transcribe")
        .arg(fixtures_dir().join("async_await.rs"))
        .arg("--fn")
        .arg("async_await")
        .output()
        .expect("CLI を起動できる");
    assert!(output.status.success());
    let text = String::from_utf8_lossy(&output.stdout);
    assert!(text.contains("関数 async_await:"));
    assert!(text.contains("async 関数 (await 2点)。"));
}

#[test]
fn version_and_help_work() {
    magia().arg("--version").assert().success();
    magia().arg("--help").assert().success();
}
